const courseData = [
  {
    id: 100,
    courseCode: "PHY101",
    course: "Physics",
    dept: "Engineering",
    instructor: "Dr. Sarah Johnson",
    credits: 3,
    description:
      "Introduction to classical mechanics, thermodynamics, and electromagnetism.",
    maxEnrollment: 50,
    currentEnrollment: 0,
  },
  {
    id: 101,
    courseCode: "MATH202",
    course: "Mathematics",
    dept: "Science",
    instructor: "Prof. Michael Chen",
    credits: 4,
    description:
      "Advanced calculus and linear algebra for engineering applications.",
    maxEnrollment: 60,
    currentEnrollment: 0,
  },
  {
    id: 102,
    courseCode: "CHEM203",
    course: "Chemistry",
    dept: "Science",
    instructor: "Dr. Emily Rodriguez",
    credits: 3,
    description: "Organic and inorganic chemistry fundamentals.",
    maxEnrollment: 40,
    currentEnrollment: 0,
  },
  {
    id: 103,
    courseCode: "CSC204",
    course: "Computer Science",
    dept: "Technology",
    instructor: "Dr. James Wilson",
    credits: 4,
    description: "Programming fundamentals, data structures, and algorithms.",
    maxEnrollment: 45,
    currentEnrollment: 0,
  },
  {
    id: 104,
    courseCode: "ECO205",
    course: "Economics",
    dept: "Social Science",
    instructor: "Prof. Lisa Thompson",
    credits: 3,
    description: "Microeconomics and macroeconomics principles.",
    maxEnrollment: 55,
    currentEnrollment: 0,
  },
  {
    id: 105,
    courseCode: "BIO206",
    course: "Biology",
    dept: "Science",
    instructor: "Dr. Robert Davis",
    credits: 3,
    description: "Cell biology, genetics, and molecular biology.",
    maxEnrollment: 50,
    currentEnrollment: 0,
  },
  {
    id: 106,
    courseCode: "MECH207",
    course: "Mechanical Engineering",
    dept: "Engineering",
    instructor: "Prof. Amanda Garcia",
    credits: 4,
    description: "Statics, dynamics, and materials science.",
    maxEnrollment: 35,
    currentEnrollment: 0,
  },
  {
    id: 107,
    courseCode: "CIV208",
    course: "Civil Engineering",
    dept: "Engineering",
    instructor: "Dr. Kevin Martinez",
    credits: 4,
    description: "Structural analysis and design principles.",
    maxEnrollment: 40,
    currentEnrollment: 0,
  },
  {
    id: 108,
    courseCode: "HIST209",
    course: "History",
    dept: "Arts",
    instructor: "Prof. Maria Lopez",
    credits: 3,
    description: "World history from ancient civilizations to modern times.",
    maxEnrollment: 60,
    currentEnrollment: 0,
  },
  {
    id: 109,
    courseCode: "PHIL210",
    course: "Philosophy",
    dept: "Arts",
    instructor: "Dr. David Brown",
    credits: 3,
    description:
      "Introduction to philosophical thinking and major philosophical questions.",
    maxEnrollment: 45,
    currentEnrollment: 0,
  },
  {
    id: 110,
    courseCode: "EE211",
    course: "Electrical Engineering",
    dept: "Engineering",
    instructor: "Prof. Jennifer Lee",
    credits: 4,
    description: "Circuit analysis, electronics, and power systems.",
    maxEnrollment: 35,
    currentEnrollment: 0,
  },
];

export default courseData;