const courseData = [
  {
    id: 100,
    courseCode: 201,
    course: "Physics",
    dept: "Engineering",
    instructor: "Dr. Sarah Johnson",
    credits: 3,
    description:
      "Introduction to classical mechanics, thermodynamics, and electromagnetism.",
    maxEnrollment: 50,
    currentEnrollment: 35,
  },
  {
    id: 101,
    courseCode: 202,
    course: "Mathematics",
    dept: "Science",
    instructor: "Prof. Michael Chen",
    credits: 4,
    description:
      "Advanced calculus and linear algebra for engineering applications.",
    maxEnrollment: 60,
    currentEnrollment: 42,
  },
  {
    id: 102,
    courseCode: 203,
    course: "Chemistry",
    dept: "Science",
    instructor: "Dr. Emily Rodriguez",
    credits: 3,
    description: "Organic and inorganic chemistry fundamentals.",
    maxEnrollment: 40,
    currentEnrollment: 28,
  },
  {
    id: 103,
    courseCode: 204,
    course: "Computer Science",
    dept: "Technology",
    instructor: "Dr. James Wilson",
    credits: 4,
    description: "Programming fundamentals, data structures, and algorithms.",
    maxEnrollment: 45,
    currentEnrollment: 45,
  },
  {
    id: 104,
    courseCode: 205,
    course: "Economics",
    dept: "Social Science",
    instructor: "Prof. Lisa Thompson",
    credits: 3,
    description: "Microeconomics and macroeconomics principles.",
    maxEnrollment: 55,
    currentEnrollment: 38,
  },
  {
    id: 105,
    courseCode: 206,
    course: "Biology",
    dept: "Science",
    instructor: "Dr. Robert Davis",
    credits: 3,
    description: "Cell biology, genetics, and molecular biology.",
    maxEnrollment: 50,
    currentEnrollment: 33,
  },
  {
    id: 106,
    courseCode: 207,
    course: "Mechanical Engineering",
    dept: "Engineering",
    instructor: "Prof. Amanda Garcia",
    credits: 4,
    description: "Statics, dynamics, and materials science.",
    maxEnrollment: 35,
    currentEnrollment: 29,
  },
  {
    id: 107,
    courseCode: 208,
    course: "Civil Engineering",
    dept: "Engineering",
    instructor: "Dr. Kevin Martinez",
    credits: 4,
    description: "Structural analysis and design principles.",
    maxEnrollment: 40,
    currentEnrollment: 31,
  },
  {
    id: 108,
    courseCode: 209,
    course: "History",
    dept: "Arts",
    instructor: "Prof. Maria Lopez",
    credits: 3,
    description: "World history from ancient civilizations to modern times.",
    maxEnrollment: 60,
    currentEnrollment: 47,
  },
  {
    id: 109,
    courseCode: 210,
    course: "Philosophy",
    dept: "Arts",
    instructor: "Dr. David Brown",
    credits: 3,
    description:
      "Introduction to philosophical thinking and major philosophical questions.",
    maxEnrollment: 45,
    currentEnrollment: 22,
  },
  {
    id: 110,
    courseCode: 211,
    course: "Electrical Engineering",
    dept: "Engineering",
    instructor: "Prof. Jennifer Lee",
    credits: 4,
    description: "Circuit analysis, electronics, and power systems.",
    maxEnrollment: 35,
    currentEnrollment: 32,
  },
];
export default courseData;
